# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, max_length=600, null=True)),
                ('d_tokens', models.CharField(blank=True, max_length=600, null=True)),
                ('d_email', models.CharField(blank=True, max_length=600, null=True)),
                ('d_status', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NgoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_name', models.CharField(blank=True, max_length=600, null=True)),
                ('n_website', models.CharField(blank=True, max_length=600, null=True)),
                ('n_email', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_milestones', models.CharField(blank=True, max_length=600, null=True)),
                ('p_total_raise', models.CharField(blank=True, max_length=600, null=True)),
                ('p_name', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('p_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NgoDB')),
            ],
        ),
    ]
