# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.CharField(blank=True, max_length=600, null=True)),
                ('amount', models.CharField(blank=True, max_length=600, null=True)),
                ('info', models.CharField(blank=True, max_length=6000, null=True)),
                ('count', models.CharField(blank=True, max_length=600, null=True)),
                ('extra1', models.CharField(blank=True, max_length=600, null=True)),
                ('extra2', models.CharField(blank=True, max_length=600, null=True)),
                ('extra3', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.CharField(blank=True, max_length=600, null=True)),
                ('rating_information', models.CharField(blank=True, max_length=600, null=True)),
                ('rating_transparency', models.CharField(blank=True, max_length=600, null=True)),
                ('rating_completion', models.CharField(blank=True, max_length=600, null=True)),
                ('rating_accuracy', models.CharField(blank=True, max_length=600, null=True)),
                ('rating5', models.CharField(blank=True, max_length=600, null=True)),
                ('rating6', models.CharField(blank=True, max_length=600, null=True)),
                ('rating7', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.CharField(blank=True, max_length=600, null=True)),
                ('extra1', models.CharField(blank=True, max_length=600, null=True)),
                ('extra2', models.CharField(blank=True, max_length=600, null=True)),
                ('extra3', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilestonesDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=600, null=True)),
                ('milestone_number', models.CharField(blank=True, max_length=600, null=True)),
                ('total_raise', models.CharField(blank=True, max_length=600, null=True)),
                ('current_raise', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.CharField(blank=True, max_length=600, null=True)),
                ('extra1', models.CharField(blank=True, max_length=600, null=True)),
                ('extra2', models.CharField(blank=True, max_length=600, null=True)),
                ('extra3', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='donordb',
            old_name='d_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donordb',
            old_name='d_name',
            new_name='extra1',
        ),
        migrations.RenameField(
            model_name='donordb',
            old_name='d_status',
            new_name='extra2',
        ),
        migrations.RenameField(
            model_name='donordb',
            old_name='d_tokens',
            new_name='extra3',
        ),
        migrations.RenameField(
            model_name='ngodb',
            old_name='n_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ngodb',
            old_name='n_name',
            new_name='extra1',
        ),
        migrations.RenameField(
            model_name='ngodb',
            old_name='n_website',
            new_name='extra2',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='p_milestones',
            new_name='extra1',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='p_name',
            new_name='extra2',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='p_total_raise',
            new_name='extra3',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='p_owner',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='donordb',
            name='name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='donordb',
            name='status',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='donordb',
            name='tokens',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='ngodb',
            name='extra3',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='ngodb',
            name='name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='ngodb',
            name='website',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='milestones',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='status',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='total_raise',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='milestonesdb',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProjectDB'),
        ),
        migrations.AddField(
            model_name='milestonereview',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DonorDB'),
        ),
        migrations.AddField(
            model_name='milestonereview',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MilestonesDB'),
        ),
        migrations.AddField(
            model_name='milestonereview',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NgoDB'),
        ),
        migrations.AddField(
            model_name='milestonereview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProjectDB'),
        ),
        migrations.AddField(
            model_name='contractdb',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DonorDB'),
        ),
        migrations.AddField(
            model_name='contractdb',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MilestonesDB'),
        ),
        migrations.AddField(
            model_name='contractdb',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NgoDB'),
        ),
        migrations.AddField(
            model_name='contractdb',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProjectDB'),
        ),
    ]
