# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180707_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodb',
            name='status',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
