# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ngodb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonesdb',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
