# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180707_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonesdb',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.NgoDB'),
            preserve_default=False,
        ),
    ]
